### ISSUE TITLE
mocap optitrack integration with mavros

### ISSUE THREAD

**Issue by andrea-nisti** [ros-drivers/mocap_optitrack#13]
Hello, I tired to integrate the mocap_optitrack node to recieve from the system with mavros (https://github.com/mavlink/mavlink) in order to send data to the robot (IRIS quadcopter). I realized looking at the flight plots that the vision data are delayed by 0.7 seconds respect to data estimated onboard. This phenomenon is not happening with a program written in qt in order to send and recieve. 

I integrated the sending Qt part in ros eliminating mavros and keeping mocap_optitrack to recieve, still same problem. 
Is it something related to publishing frequency of mocap_optitrack or maybe buffers senting copies of the same data? Any help is welcome.

**Comment by orhirshfeld** [comment]
Try to check for smoothing filter of the object properties in Motive.
