### ISSUE TITLE
Getting mocap_optitrack to work with motive 1.9 and ros hydro

### ISSUE THREAD

**Issue by ngonzo95** [ros-drivers/mocap_optitrack#20]
Hi,

I trying to get data steaming between motive 1.9 and ROS hydro working. I set the multicast interface to the IP of the computer with ROS on it and I keep getting the following error: 

Joining multicast group 192.168.1.10...
terminate called after throwing an instance of 'SocketException'
     what(): Failed to set socket option: EINVAL

do you know what could be causing this? I have tried this on both the master branch and the new-and-old-support branch

Thanks, Nick

**Comment by xuyongzhi** [comment]
I solved this error. The multicast group ip set in motive should not be the ip of the computer running motive. But should be another one like 239.255.42.99.
