### ISSUE TITLE
No timestamp when using mocap_optitrack 

### ISSUE THREAD

**Issue by pchatrath** [ros-drivers/mocap_optitrack#22]
I use mocap_optitrack to get data from Motive to ROS. I implemented the complete software pipeline for my PX4 uav. I get mocap timeout and xy timeout error. I figured out locap position estimator in px4 requires difference between 2 timestamps to be less than 0.2s. 

I get timestamps in my topic published through mocap_optitrack. But I dot get it why I get mocap timeout error. What am I missing.  Any ideas?

**Comment by jhabhargav26** [comment]
I am trying to get the same. The natnet documentation says that the packet includes the timestamp from Motive but I don't know how to decode it. Any leads would be highly appreciated. Thanks

**Comment by tonybaltovski** [comment]
See https://github.com/ros-drivers/mocap_optitrack/issues/12 for a previous discussion on this.
