### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by Margarita2Z** [ros-drivers/mocap_optitrack#30]
hello, i got this message once i tried to install this package.:

Could not find a package configuration file provided by "urdfdom_py" with
  any of the following names:

    urdfdom_pyConfig.cmake
    urdfdom_py-config.cmake

is there a solution to this?

**Comment by tonybaltovski** [comment]
Hi,
There is nothing in this package that depends on `urdf_parser_py`.  Try to compile in a clean workspace.

**Comment by Margarita2Z** [comment]
Hey,
Thank you. It worked.



Get Outlook for Android<https://aka.ms/ghei36>

________________________________
