### ISSUE TITLE
Node failure when data streaming

### ISSUE THREAD

**Issue by nickoly9** [ros-drivers/mocap_optitrack#31]
The mocap node dies and exits when I begin to stream data to the IP that the node is running on. I do not have the same issue when I stream data to a device that is not running the current master but is a few commits behind master. But both devices running the current master have the same problem. 
Here is the exit error that is thrown from one of the non-working devices:
```
================================================================================REQUIRED process [mocap_node-2] has died!
process has died [pid 9134, exit code -11, cmd /home/nick/catkin_ws/devel/lib/mocap_optitrack/mocap_node __name:=mocap_node __log:=/home/nick/.ros/log/844edfa6-c8b8-11e7-93e1-e4f89c290d01/mocap_node-2.log].
log file: /home/nick/.ros/log/844edfa6-c8b8-11e7-93e1-e4f89c290d01/mocap_node-2*.log
Initiating shutdown!
================================================================================
```

**Comment by zhaoxiaowei1013** [comment]
hello，nick
how to deal with this question？
