### ISSUE TITLE
Optitrack and Crazyflie communication

### ISSUE THREAD

**Issue by s3xyxavy** [ros-drivers/mocap_optitrack#33]
Hi, 

I am currently working on a project with in having a communication with mocap and crazyflie. I realized that when I was checking the quarternions on RVIZ, the quarternion for rotation in y plane is inverted is there any way I could change the parameter to make the y result inverted ( + / - ) sign. TIA =)

Warm Regards,
Xavier

**Comment by tonybaltovski** [comment]
What version of Motive or Tracking tools are you using?

**Comment by s3xyxavy** [comment]
Hi Tony,
 
I am using 1.7 On Motive, there isn’t toggle for y-up on motive for this version. 

Warm regards,
Xavier

**Comment by s3xyxavy** [comment]
Hi Tony, where do I look at the new-and-old-support-updated branch?

**Comment by tonybaltovski** [comment]
https://github.com/ros-drivers/mocap_optitrack/tree/new-and-old-support-updated
