### ISSUE TITLE
Incorrect timestamp

### ISSUE THREAD

**Issue by 321thijs123** [ros-drivers/mocap_optitrack#64]
The timestamp added to the published messages is the time of publishing, not the time optitrack determined the pose.

**Comment by 321thijs123** [comment]
I have been working on a fix, in this fork: https://github.com/321thijs123/mocap_optitrack
I have not been able to test it yet.

**Comment by 321thijs123** [comment]
Fixed in merge commit https://github.com/ros-drivers/mocap_optitrack/commit/302cadf8fb06cce4a52adc0f9ea115e2168c7f92

**Comment by ghoshsuman** [comment]
Hi. I was wondering if this fix of using the optitrack time instead of ROS time at the host machine is also implemented in the master branch? I am basically looking for a solution to this in ROS Noetic. Thanks!

**Comment by 321thijs123** [comment]
Hi @ghoshsuman,
It has not been implemented in the master branch. You could check out the changes made in [302cadf](https://github.com/ros-drivers/mocap_optitrack/commit/302cadf8fb06cce4a52adc0f9ea115e2168c7f92) and implement the same in the ROS Noetic version.
If you have any specific questions about the code feel free to ask!
