### ISSUE TITLE
Compiling problem with ament_cmake

### ISSUE THREAD

**Issue by dtbinh** [ros-drivers/mocap_optitrack#71]
I have Ubuntu 18.04 and ROS melodic
I follow the following steps:
   cd ~/catkin_ws/src
   git clone https://github.com/ros-drivers/mocap_optitrack.git
  cd ..
  catkin build
  
  But I receive the following result:
 
![ament_cmake](https://user-images.githubusercontent.com/10114201/157252401-7dadb5f3-cd58-4853-ab2e-2c0b39d0aecd.png)

I don't know how to build the packages.

**Comment by tonybaltovski** [comment]
Use the `master` branch since it is for ROS1 and `foxy-devel` is for ROS2.
