### ISSUE TITLE
Update to ROS2 Humble

### ISSUE THREAD

**Issue by ljaniec** [ros-drivers/mocap_optitrack#74]
Hello, 

Are there plans to port it to the new LTS version of ROS2, `ROS 2 Humble`?

Best,
Łukasz Janiec

**Comment by tonybaltovski** [comment]
The foxy-devel branch supports Humble.

**Comment by Berayksl** [comment]
When I launch the mocap node on ROS2 Humble, it gets stuck at:

[mocap_node-1] [INFO] [1717540789.899215214] [mocap_node]: Enabling non-blocking I/O

What might be the issue?
